config/routes.rb
Rails.application.routes.draw do
    root "sessions#new"
    get '/:locale'   => 'sessions#new',as:"locale" 
    get '/' => redirect("/ja")
    post '/',        to: 'sessions#create'
    get 'password_resets/new'
    get 'password_resets/edit'
  scope ":/locale", locale:/en|ja/ do
  # scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    get  '/',        to: 'sessions#new'
    post '/',        to: 'sessions#create'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/privacy', to: 'static_pages#privacy'
    get  '/term',    to: 'static_pages#term'
    get  '/language',to: 'static_pages#language'
    get  '/search',  to: 'static_pages#search'
    get  '/searchresult', to: 'static_pages#searchresult'
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    delete '/logout',    to: 'sessions#destroy'
    get  '/tester',      to: 'tests#new'
    post '/tester',      to: 'tests#create'
    get  '/mytests',     to: 'tests#my_index'
    get  '/mytests/:id', to: 'tests#my_show'
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :tests do
      resources :questions do
        member do
          get :answerring
          post :post_answerring
        end
        resources :selects, :answers, only: [:new, :create, :edit, :destroy]
      end
    end
    resources :testeds do
      resources :tests do
        resources :answers, only: [:index, :show, :destroy]
      end
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to t(:"Top"),    root_path %></li>
      <li><%= link_to t(:"Help"),    help_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= t(:"Language") %><b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "English", locale_path(locale:"en") %></li>
          <li><%= link_to "日本語", locale_path(locale:"ja") %></li>
        </ul>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-expand-sm mt-3 mb-3">
  <button id='scroll_top' class="btn_fix_top btn-lg btn-primary">▲</button>
  <button id='scroll_bottom' class="btn_fix_bottom btn-lg btn-primary">▼</button>
  <div class="container">
    <%= link_to "MyTest", root_path, id: "logo" %>
    <nav class="pc-nav">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/header_menu' %>
      </ul>
    </nav>
    <nav class="sp-nav">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/header_menu_sp' %>
      </ul>
    </nav>
    <div id="hamburger">
      <span></span>
    </div>
  </div>
</header>

app/views/layouts/_header_menu.html.erb
<li><%= link_to t(:"Top"),  root_path %></li>
<li><%= link_to t(:"Help"), help_path %></li>
<% if logged_in? %>
  <li><%= link_to t(:"Users"), users_path %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t(:"Account") %> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to t(:"Profile"), current_user %></li>
      <li><%= link_to t(:"Settings"), edit_user_path(current_user) %></li>
      <li class="divider"></li>
      <li>
        <%= link_to t(:"Log out"), logout_path, method: :delete %>
      </li>
    </ul>
  </li>
<% else %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t(:"Log in") %><b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to t(:"Log in"), root_path %></li>
      <li><%= link_to t(:"Sign up"), new_user_path %></li>
    </ul>
  </li>
<% end %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <%= t(:"Language") %><b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to "English", locale_path(locale:"en") %></li>
    <li><%= link_to "日本語", locale_path(locale:"ja") %></li>
  </ul>
</li>

app/views/layouts/_header_menu_sp.html.erb
<li><%= link_to t(:"Top"),  root_path %></li>
<li><%= link_to t(:"Help"), help_path %></li>
<% if logged_in? %>
  <li><%= link_to t(:"Users"), users_path %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <%= t(:"Account") %> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to t(:"Profile"), current_user %></li>
      <li><%= link_to t(:"Settings"), edit_user_path(current_user) %></li>
      <li class="divider"></li>
      <li>
        <%= link_to t(:"Log out"), logout_path, method: :delete %>
      </li>
    </ul>
  </li>
<% else %>
  <li class="dropdown">
    <li><%= link_to t(:"Log in"), root_path %></li>
    <li><%= link_to t(:"Sign up"), new_user_path %></li>
    <li><%= link_to "English", locale_path(locale:"en") %></li>
    <li><%= link_to "日本語", locale_path(locale:"ja") %></li>
    <li class="close">閉じる</li>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">-->
    <!-- Bootstrap JOptional theme -->
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">-->
    <!-- Bootstrap JavaScript -->
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>-->
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--slick スライドショー用-->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
 　  <script type="text/javascript" src="http://code.jquery.com/jquery-3.1.0.min.js"></script>
    <!--スライドショー-->
    <script>
    $(function(){
      $('.single-item').slick({
        accessibility: true,
        autoplay: true,
        autoplaySpeed: 5000,
        dots: true,
        fade: true,
      });
    });
    </script>
    <!-- スムーズスクロール部分の記述 -->
    <script>
    $(function(){
      // #で始まるアンカーをクリックした場合に処理
      $('a[href^=#]').click(function() {
        // スクロールの速度
        var speed = 500; // ミリ秒
        // アンカーの値取得
        var href= $(this).attr("href");
        // 移動先を取得
        var target = $(href == "#" || href == "" ? 'html' : href);
        // 移動先を数値で取得
        var position = target.offset().top - 100;
        // スムーススクロール
        $('body,html').animate({scrollTop:position}, speed, 'swing');
        return false;
       });
    });
    </script>
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
    <script>
    $(function() {
      const hum = $('#hamburger, .close')
      const nav = $('.sp-nav')
      hum.on('click', function(){
         nav.toggleClass('toggle');
      });
    });
    </script>
  </head>
  <body>
    <div id="top_page"></div> <!-- 画面トップへのスクロール用 -->
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <div id="bottom_page"></div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </body>
  <script>
    document.getElementById('scroll_top').addEventListener('click',function(){
      $("html,body").animate({scrollTop:$('#top_page').offset().top});
    });
    document.getElementById('scroll_bottom').addEventListener('click',function(){
      $("html,body").animate({scrollTop:$('#bottom_page').offset().top});
    });
  </script>
</html>